# Neo4j
neo4j:
  image: kbastani/docker-neo4j
  ports:
    - "7474:7474"
#concept-test
concepts:
  image: ynuae/concepts-test
  links:
    - neo4j:neo4j
  environment:
    - NEO_HOST=http://neo4j:7474